export const users = [
  {
    id: 11,
    name: 'Alice',
    surname: 'Johnson',
    gender: 'women',
    position: 'CEO',
    grade: 1,
    bossId: null,
  },
  {
    id: 12,
    name: 'Bob',
    surname: 'Smith',
    gender: 'men',
    position: 'QA Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 13,
    name: 'Charlie',
    surname: 'Brown',
    gender: 'men',
    position: 'Developer Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 14,
    name: 'Diana',
    surname: 'Williams',
    gender: 'women',
    position: 'Designer Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 15,
    name: 'Ethan',
    surname: 'Davis',
    gender: 'men',
    position: 'Manager Head',
    grade: 2,
    bossId: 11,
  },
  {
    id: 16,
    name: 'Fiona',
    surname: 'Miller',
    gender: 'women',
    position: 'QA Lead 1',
    grade: 3,
    bossId: 12,
  },
  {
    id: 17,
    name: 'George',
    surname: 'Wilson',
    gender: 'men',
    position: 'QA Lead 2',
    grade: 3,
    bossId: 12,
  },
  {
    id: 18,
    name: 'Hannah',
    surname: 'Moore',
    gender: 'women',
    position: 'QA Lead 3',
    grade: 3,
    bossId: 12,
  },
  {
    id: 19,
    name: 'Isaac',
    surname: 'Taylor',
    gender: 'men',
    position: 'Developer Lead 1',
    grade: 3,
    bossId: 13,
  },
  {
    id: 20,
    name: 'Julia',
    surname: 'Anderson',
    gender: 'women',
    position: 'Developer Lead 2',
    grade: 3,
    bossId: 13,
  },
  {
    id: 21,
    name: 'Lucas',
    surname: 'Evans',
    gender: 'men',
    position: 'Developer Lead 3',
    grade: 3,
    bossId: 13,
  },
  {
    id: 22,
    name: 'Isabella',
    surname: 'Harris',
    gender: 'women',
    position: 'Designer Lead 1',
    grade: 3,
    bossId: 14,
  },
  {
    id: 23,
    name: 'James',
    surname: 'Martin',
    gender: 'men',
    position: 'Designer Lead 2',
    grade: 3,
    bossId: 14,
  },
  {
    id: 24,
    name: 'Emily',
    surname: 'Clark',
    gender: 'women',
    position: 'Designer Lead 3',
    grade: 3,
    bossId: 14,
  },
  {
    id: 25,
    name: 'Mason',
    surname: 'Walker',
    gender: 'men',
    position: 'Manager Lead 1',
    grade: 3,
    bossId: 15,
  },
  {
    id: 26,
    name: 'Sophia',
    surname: 'Lewis',
    gender: 'women',
    position: 'Manager Lead 2',
    grade: 3,
    bossId: 15,
  },
  {
    id: 27,
    name: 'Benjamin',
    surname: 'Hall',
    gender: 'men',
    position: 'Manager Lead 3',
    grade: 3,
    bossId: 15,
  },
  {
    id: 28,
    name: 'Olivia',
    surname: 'Allen',
    gender: 'women',
    position: 'QA Senior',
    grade: 4,
    bossId: 16,
  },
  {
    id: 29,
    name: 'Ethan',
    surname: 'Young',
    gender: 'men',
    position: 'QA Middle',
    grade: 4,
    bossId: 16,
  },
  {
    id: 30,
    name: 'Liam',
    surname: 'King',
    gender: 'men',
    position: 'QA Junior',
    grade: 4,
    bossId: 16,
  },

  // 30 новых сотрудников
  {
    id: 31,
    name: 'Daniel',
    surname: 'Scott',
    gender: 'men',
    position: 'QA Senior',
    grade: 4,
    bossId: 17,
  },
  {
    id: 32,
    name: 'Charlotte',
    surname: 'Adams',
    gender: 'women',
    position: 'QA Middle',
    grade: 4,
    bossId: 17,
  },
  {
    id: 33,
    name: 'Henry',
    surname: 'Baker',
    gender: 'men',
    position: 'QA Junior',
    grade: 4,
    bossId: 17,
  },
  {
    id: 34,
    name: 'Amelia',
    surname: 'Gonzalez',
    gender: 'women',
    position: 'QA Senior',
    grade: 4,
    bossId: 18,
  },
  {
    id: 35,
    name: 'Jack',
    surname: 'Nelson',
    gender: 'men',
    position: 'QA Middle',
    grade: 4,
    bossId: 18,
  },
  {
    id: 36,
    name: 'Lucas',
    surname: 'Carter',
    gender: 'men',
    position: 'QA Junior',
    grade: 4,
    bossId: 18,
  },
  {
    id: 37,
    name: 'Mia',
    surname: 'Mitchell',
    gender: 'women',
    position: 'Developer Senior',
    grade: 4,
    bossId: 19,
  },
  {
    id: 38,
    name: 'Noah',
    surname: 'Perez',
    gender: 'men',
    position: 'Developer Middle',
    grade: 4,
    bossId: 19,
  },
  {
    id: 39,
    name: 'Ella',
    surname: 'Roberts',
    gender: 'women',
    position: 'Developer Junior',
    grade: 4,
    bossId: 19,
  },
  {
    id: 40,
    name: 'William',
    surname: 'Turner',
    gender: 'men',
    position: 'Developer Senior',
    grade: 4,
    bossId: 20,
  },
  {
    id: 41,
    name: 'Zoe',
    surname: 'Phillips',
    gender: 'women',
    position: 'Developer Middle',
    grade: 4,
    bossId: 20,
  },
  {
    id: 42,
    name: 'Aiden',
    surname: 'Campbell',
    gender: 'men',
    position: 'Developer Junior',
    grade: 4,
    bossId: 20,
  },
  {
    id: 43,
    name: 'Harper',
    surname: 'Edwards',
    gender: 'women',
    position: 'Developer Senior',
    grade: 4,
    bossId: 21,
  },
  {
    id: 44,
    name: 'Gabriel',
    surname: 'Collins',
    gender: 'men',
    position: 'Developer Middle',
    grade: 4,
    bossId: 21,
  },
  {
    id: 45,
    name: 'Elijah',
    surname: 'Stewart',
    gender: 'men',
    position: 'Developer Junior',
    grade: 4,
    bossId: 21,
  },
  {
    id: 46,
    name: 'Nathan',
    surname: 'Morris',
    gender: 'men',
    position: 'Designer Senior',
    grade: 4,
    bossId: 22,
  },
  {
    id: 47,
    name: 'Lucy',
    surname: 'Rogers',
    gender: 'women',
    position: 'Designer Middle',
    grade: 4,
    bossId: 22,
  },
  {
    id: 48,
    name: 'Madison',
    surname: 'Reed',
    gender: 'women',
    position: 'Designer Junior',
    grade: 4,
    bossId: 22,
  },
  {
    id: 49,
    name: 'Owen',
    surname: 'Cook',
    gender: 'men',
    position: 'Designer Senior',
    grade: 4,
    bossId: 23,
  },
  {
    id: 50,
    name: 'Hannah',
    surname: 'Bell',
    gender: 'women',
    position: 'Designer Middle',
    grade: 4,
    bossId: 23,
  },
  {
    id: 51,
    name: 'Carter',
    surname: 'Murphy',
    gender: 'men',
    position: 'Designer Junior',
    grade: 4,
    bossId: 23,
  },
  {
    id: 52,
    name: 'Sophie',
    surname: 'Bailey',
    gender: 'women',
    position: 'Designer Senior',
    grade: 4,
    bossId: 24,
  },
  {
    id: 53,
    name: 'David',
    surname: 'Rivera',
    gender: 'men',
    position: 'Designer Middle',
    grade: 4,
    bossId: 24,
  },
  {
    id: 54,
    name: 'Isla',
    surname: 'Cooper',
    gender: 'women',
    position: 'Designer Junior',
    grade: 4,
    bossId: 24,
  },

  {
    id: 55,
    name: 'Harper',
    surname: 'Scott',
    gender: 'men',
    position: 'Manager Senior',
    grade: 4,
    bossId: 25,
  },
  {
    id: 56,
    name: 'Charlotte',
    surname: 'Campbell',
    gender: 'women',
    position: 'Manager Middle',
    grade: 4,
    bossId: 25,
  },
  {
    id: 57,
    name: 'Elijah',
    surname: 'Baker',
    gender: 'men',
    position: 'Manager Junior',
    grade: 4,
    bossId: 25,
  },
  {
    id: 58,
    name: 'Sophie',
    surname: 'Gonzalez',
    gender: 'women',
    position: 'Manager Senior',
    grade: 4,
    bossId: 26,
  },
  {
    id: 59,
    name: 'Nathan',
    surname: 'Nelson',
    gender: 'men',
    position: 'Manager Middle',
    grade: 4,
    bossId: 26,
  },
  {
    id: 60,
    name: 'Reed',
    surname: 'Carter',
    gender: 'men',
    position: 'Manager Junior',
    grade: 4,
    bossId: 26,
  },
  {
    id: 61,
    name: 'Mia',
    surname: 'Murphy',
    gender: 'women',
    position: 'Manager Senior',
    grade: 4,
    bossId: 27,
  },
  {
    id: 62,
    name: 'Noah',
    surname: 'Rivera',
    gender: 'men',
    position: 'Manager Middle',
    grade: 4,
    bossId: 27,
  },
  {
    id: 63,
    name: 'Mitchell',
    surname: 'Roberts',
    gender: 'women',
    position: 'Manager Junior',
    grade: 4,
    bossId: 27,
  },
];
